
find_package(PkgConfig)
pkg_check_modules(PC_LIBSODIUM REQUIRED QUIET libsodium)

find_path(LIBSODIUM_INCLUDE_DIR sodium.h
	HINTS ${PC_LIBSODIUM_INCLUDEDIR} ${PC_LIBSODIUM_INCLUDE_DIRS})

find_library(LIBSODIUM_LIBRARY sodium
	HINTS ${PC_LIBSODIUM_LIBDIR} ${PC_LIBSODIUM_LIBRARY_DIRS})

set(LIBSODIUM_LIBRARIES ${LIBSODIUM_LIBRARY})
set(LIBSODIUM_INCLUDE_DIRS ${LIBSODIUM_INCLUDE_DIR})
include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(LIBSODIUM DEFAULT_MSG LIBSODIUM_LIBRARIES LIBSODIUM_INCLUDE_DIRS)

mark_as_advanced(LIBSODIUM_INCLUDE_DIR LIBSODIUM_LIBRARY)
