language: c

compiler:
  - clang
  - gcc


before_script:
  - git clone git://github.com/jedisct1/libsodium.git
  - cd libsodium
  - git checkout tags/1.0.18
  - ./autogen.sh
  - ./configure
  - make check
  - sudo make install
  - cd ..
  - mkdir .build
  - cd .build
  - cmake ..
  - make

script:
  - ./shadowvpn -h
